name: Android Build

on:
  push:
    tags:
      - "*.*.*"
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build appbundle --release

      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（name.zip）
          name: android
          # 保存するファイル
          path: ./build/app/outputs/
          # 保存期間（日）
          retention-days: 1